FROM node:15.11 AS setup

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

FROM setup AS builder

RUN yarn install --frozen-lockfile

COPY . ./

RUN yarn build

FROM node:15.11-alpine

ENV NODE_ENV=production
ENV HOST=0.0.0.0

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --frozen-lockfile
RUN yarn cache clean --all

COPY --from=builder /app .

EXPOSE 8000

CMD yarn start