version: '3.7'

services: 
  backend:
    build: 
      context: ./server
      target: setup
    volumes:
      - ./server:/app
    command: /bin/sh -c "yarn; yarn dev"
    stdin_open: true
    tty: true
    restart: 'no'
  
  frontend:
    build: 
      context: ./client
      target: setup
    volumes: 
      - ./client:/app
    command: /bin/sh -c "yarn; yarn start"
    stdin_open: true
    tty: true
    restart: 'no'