version: '3.7'

services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    ports: 
      - "5000:5000"
      - "5500:5500"
  
  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports: 
      - "8000:8000"


networks: 
  default:
    name: the_bombermann