FROM node:20-alpine AS setup

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

FROM setup AS builder

RUN yarn install --frozen-lockfile

COPY . ./

RUN yarn build

FROM node:20-alpine

ENV NODE_ENV=production
ENV HOST=0.0.0.0

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --frozen-lockfile
RUN yarn cache clean --all

COPY --from=builder /app .

EXPOSE 5000
EXPOSE 5500

CMD yarn start