FROM nginx:1.17-alpine

WORKDIR /app

COPY ./errors /usr/share/nginx/html/errors
COPY ./config/conf.d /etc/nginx/conf.d
COPY ./config/nginx.conf ./nginx.conf

CMD /bin/sh -c "envsubst < ./nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
